imports:
  - { resource: common/context.yml }
  - { resource: common/handler.yml }
  - { resource: common/segment.yml }
  - { resource: common/repository.yml }
  - { resource: common/factory.yml }
  - { resource: common/adapter.yml }
  - { resource: common/config.yml }

services:
  ps_googleshopping:
    class: 'Ps_googleshopping'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'ps_googleshopping'
