services:
  PrestaShop\Module\PsxMarketingWithGoogle\Conversion\EnhancedConversionToggle:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Conversion\EnhancedConversionToggle
    public: true
    arguments:
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Adapter\ConfigurationAdapter'
