services:
  PrestaShop\Module\PsxMarketingWithGoogle\Provider\CategoryProvider:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Provider\CategoryProvider
    arguments:
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Repository\CategoryRepository'

  PrestaShop\Module\PsxMarketingWithGoogle\Provider\PurchaseEventDataProvider:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Provider\PurchaseEventDataProvider
    arguments:
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Provider\ProductDataProvider'

  PrestaShop\Module\PsxMarketingWithGoogle\Provider\ProductDataProvider:
    class: 'PrestaShop\Module\PsxMarketingWithGoogle\Provider\ProductDataProvider'
    arguments:
      - '@psxmarketingwithgoogle.context'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Provider\CategoryProvider'
