services:
  PrestaShop\Module\PrestashopGoogleShopping\Provider\MultishopDataProvider:
    class: PrestaShop\Module\PrestashopGoogleShopping\Provider\MultishopDataProvider
    arguments:
      - '@PrestaShop\Module\PrestashopGoogleShopping\Repository\ShopRepository'
      - '@PrestaShop\Module\PrestashopGoogleShopping\Tracker\Segment'
