services:
  PrestaShop\Module\PsxMarketingWithGoogle\Handler\ErrorHandler:
    class: PrestaShop\Module\PsxMarketingWithGoogle\Handler\ErrorHandler
    arguments:
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Adapter\ConfigurationAdapter'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Builder\CarrierBuilder'
      - '@PrestaShop\Module\PsxMarketingWithGoogle\Repository\CarrierRepository'
