name: Build & Release draft

on: [push, pull_request]

env:
  PS_IMG_VERSION: prestashop/prestashop:1.7-7.4-apache

jobs:
  build:
    name: build dependencies & create artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Build JS dependencies
        uses: PrestaShopCorp/github-action-build-js/12@v1.0
        with:
          cmd: npm
          path: ./_dev
      - name: Install composer dependencies
        run: composer install --no-dev -o
      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@v1.0
      - name: Create & upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: ${{ github.event.repository.name }}
          path: ../

  update_release_draft:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
    steps:
      - id: release_info
        uses: toolmantim/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ci_cd_stable:
    name: CI/CD push production ps_googleshopping
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    if: github.event_name == 'push' && github.event.ref == 'refs/heads/master'
    steps:

      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ github.event.repository.name }}

      - name: Copy modules
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "build"

      - name: Delete old modules 1.7
        continue-on-error: true
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=googleshopping") rm -rf modules/ps_googleshopping'

      - name: Move modules
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'cp -R build/ps_googleshopping/ps_googleshopping ${{ secrets.MODULE_PATH }}'
            sudo su -c 'chown -R www-data:www-data ${{ secrets.MODULE_PATH }}/ps_googleshopping'
      - name: Install modules
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=googleshopping") bin/console prestashop:module uninstall ps_googleshopping || true'
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=googleshopping") bin/console prestashop:module install ps_googleshopping'
      - name: Clear cache
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=googleshopping") bin/console cache:cl'
            sudo su -c 'docker exec $(docker ps -q -f "ancestor=${{ env.PS_IMG_VERSION }}" -f "name=googleshopping") chmod -R 777 var/cache var/logs'
