name: CDN Publish

on:
  release:
    types: [prereleased, released]

jobs:
  publish:
    name: CDN publish
    runs-on: ubuntu-latest
    steps:
      - name: Get tag
        id: get_tag
        run: echo ::set-output name=TAG::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Trigger storage
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: metrics-storage.yml
          repo: PrestaShopCorp/services-deployment
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: 'refs/heads/main'
          inputs: '{ "version": "${{ steps.get_tag.outputs.TAG }}", "nodeVersion": "14", "vuejsPath": "_dev/apps/metrics", "vuejsBuildPath": "views", "isRelease": "${{ !github.event.release.prerelease && true || false }}" }'
