# based on .github/workflows/chromatic.yml

# Workflow name
name: 'Chromatic'

# Event for the workflow
on:
  pull_request_review:
    types: [submitted]
    paths:
      - '_dev/**'

# List of jobs
jobs:
  chromatic-deployment:
    # Conditions
    if: |
      github.event.review.state == 'approved'
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
        # 👇 Version 2 of the action
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history
      - name: Install dependencies
        run: |
          cd _dev
          npm install
        # Tests are mandatory to build storybook
      - name: Run tests
        run: |
          cd _dev
          npm run test:generate-output
        # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          workingDir: ./_dev
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
