name: JS tests
on: [push, pull_request]
jobs:
  js-linter:
    name: JS linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Lint JS files
        uses: PrestaShopCorp/github-action-lint-js/12@v1.0
        with:
          cmd: npm
          path: ./_dev

  unit-tests:
    name: JS Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install & run
        run: |
          cd _dev
          npm install
          npm run test:unit
