name: JS tests
on: [push, pull_request]
jobs:
  js-linter:
    name: JS linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: pnpm
          cache-dependency-path: '_dev/pnpm-lock.yaml'

      - name: Lint JS files
        working-directory: _dev
        run: |
          pnpm install
          pnpm -r lint

  unit-tests:
    name: JS Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: pnpm
          cache-dependency-path: '_dev/pnpm-lock.yaml'

      - name: Install & run
        working-directory: _dev
        run: |
          pnpm install
          pnpm -r test:unit
