name: Publish for integration

on:
  release:
    types: [published]

jobs:
  upload_release_asset_integration:
    name: Upload the integration zip asset to the release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v1
        with:
          name: ${{ github.event.repository.name }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCLOUD_PROJECT_INTEGRATION }}
          service_account_key: ${{ secrets.G_CREDENTIAL_INTEGRATION }}
          export_default_credentials: true

      - name: Copy env files
        run: |
          gcloud components install beta
          gcloud beta secrets versions access latest --secret="googleshopping-module" > ps_googleshopping/ps_googleshopping/.env
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.G_CREDENTIAL_INTEGRATION }}

      - name: Prepare the integration zip
        run: |
          cd ${{ github.event.repository.name }}
          zip -r ${{ github.event.repository.name }}_integration.zip ${{ github.event.repository.name }}  -x '*.git*'
      - name: Publish the integration zip
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ github.event.repository.name }}/${{ github.event.repository.name }}_integration.zip
          asset_name: ${{ github.event.repository.name }}_integration.zip
          asset_content_type: application/zip
